[package]
name = "rust-sqlx-multiple-databases"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.89"
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio", "migrate", "macros"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
